POST https://localhost:7113/api/Account/refreshtoken 
Content-Type: application/json

{
  "userId": "6dad4c8f-3c66-4f1c-8ba3-6e4fffd27419",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBob3RlbGFwaS5jb20iLCJqdGkiOiI0M2FlYTBmMS02NWU4LTQ4YmItYjIzZS1lZjhmNTdkMTU3YjUiLCJlbWFpbCI6ImFkbWluQGhvdGVsYXBpLmNvbSIsInVpZCI6IjZkYWQ0YzhmLTNjNjYtNGYxYy04YmEzLTZlNGZmZmQyNzQxOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJleHAiOjE2OTkxODMyMDAsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.FjgYzBBxPDpNYenc8bsV4Zd84doWUisPy_IRv8h8wgY",
  "refreshToken": "CfDJ8ESQWSggB31GvRkKlCNUaiVdsnxZaShqbqbggnqV4+zD+d+P2a7OU62p2w5MS7cY1rFBdrhb3vAqgIN27sVO6z71mlLow9WU6c06YP58Pv4XjPwo6eHGy3GkS4qOg4G9TQRgoXkafP0pNPs89zrXOxVb8HmeKOz1Wu+n3SzfnKh1L/guPhM0FBjNhox2txucj9gvGMEnTkPMkHe8IgD43Tulrtk1mkrqnulqTzlBtTac"
}