DELETE https://localhost:7113/api/countries/7
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBob3RlbGFwaS5jb20iLCJqdGkiOiI4MzVjYTMyZC1jNzQ2LTQ5NTUtYmI4OS0zMWNlZDQ2YTg5NzEiLCJlbWFpbCI6ImFkbWluQGhvdGVsYXBpLmNvbSIsInVpZCI6IjZkYWQ0YzhmLTNjNjYtNGYxYy04YmEzLTZlNGZmZmQyNzQxOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJleHAiOjE2OTkxNzkzMjYsImlzcyI6IkhvdGVsTGlzdGluZ0FQSSIsImF1ZCI6IkhvdGVsTGlzdGluZ0FQSUNsaWVudCJ9.2POuxS3vMeCX_STyLWz0BeCKBF_8AKaIqB9G9xUADXM
Content-Type: application/json